URL_SERVICE = "https://cnt-9cdae231-6f1a-4eec-ba06-6dce0a4cf15f.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
CREATE_USER_PATH = "/api/v1/users"
KITS_PATH = "/api/v1/kits"
CREATE_KITS_PATH = "/api/v1/kits"